config/routes.rb
Qrcode::Application.routes.draw do

    get "splash/splash"

    devise_for :users

    match "/menus/:id/edit_metric", :controller => 'menus', :action => 'edit_metric'
    match "/menus/:id/report", :controller => 'menus', :action => 'report'
    match "/menus/view/:id", :controller => 'splash', :action => 'show', :as => 'view_menu'
    match "/menus/help/:id", :controller => 'splash', :action => 'help', :as => 'help_menu'
    resources :menus

    root :to => "splash#splash"
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  validates :label, :presence => true
  belongs_to :user, :class_name => User
  has_many :menu_items
  has_many :metric_dates, :order => 'showdate'

  accepts_nested_attributes_for :menu_items, :metric_dates, :allow_destroy => true
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  # TODO: don't auth user on menu show
  before_filter :authenticate_user!, :mailer_set_url_options

  # GET /menus
  # GET /menus.json
  def index
    @menus = current_user().menus

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @menus }
    end
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
    @menu = Menu.find(params[:id])
    @title = @menu.label

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @menu }
    end
  end

  # GET /menus/new
  # GET /menus/new.json
  def new
    @menu = Menu.new
    @menu.menu_items.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @menu }
    end
  end

  # GET /menus/1/edit
  def edit
    @menu = Menu.find(params[:id])

  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(params[:menu])

    respond_to do |format|
      if @menu.save
        @menu.bitly_url = shorten(view_menu_url(:id=>@menu.id))
        @menu.save

        format.html { redirect_to edit_menu_path(@menu), notice: 'Menu was successfully created.' }
        format.json { render json: @menu, status: :created, location: @menu }
      else
        format.html { render action: "new" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /menus/1
  # PUT /menus/1.json
  def update

    @menu = Menu.find(params[:id])

    respond_to do |format|
      @menu.bitly_url = shorten(view_menu_url(:id=>@menu.id))
      if @menu.update_attributes(params[:menu])
        format.html { redirect_to menus_url, notice: 'Menu was successfully updated.' }
        format.json { head :ok }
      elsif params[:menu][:metric_dates_attributes].length > 0
        format.html { render action: "edit_metric" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      else
        format.html { render action: "edit" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy

    respond_to do |format|
      format.html { redirect_to menus_url }
      format.json { head :ok }
    end
  end

  
  def edit_metric
    @menu = Menu.find(params[:id])

    types = []
    Qrcode::Application.config.metric_types.each do |metric_type|
      types.push(metric_type)
    end
    @metric_types = ActiveSupport::JSON.encode types
    @metric_types = "var metric_types = " + @metric_types
    
    if @menu.metric_dates.length == 0
      @menu.metric_dates.build
      logger.info @menu.metric_dates
      md = @menu.metric_dates[0]


      md.metrics = []
      Qrcode::Application.config.metric_types.each do |metric_type| 
        metric = Metric.new
        metric.metric = metric_type
        metric.metric_date_id = md.id
        md.metrics.push(metric)
      end
    end
  end
 
  def report
    @menu = Menu.find(params[:id])

    @totals = {}
    @donors_by_date_dates = []
    @donors_by_date = []
    @totals['Donations'] = 0
    @totals['Total Audience'] = 0
    @menu.metric_dates.each do |metric_date|

      @donors_by_date_dates.push(metric_date.showdate.strftime('%b %-d'))

      donation_quantity = 0
      total_quantity = 0

      metric_date.metrics.each do |metric|
        if @totals[metric.metric].nil?
          @totals[metric.metric] = 0
        end
        @totals[metric.metric] += metric.quantity

        if metric.metric == 'Donations'
          donation_quantity = metric.quantity
        elsif metric.metric == 'Total Audience'
          total_quantity = metric.quantity
        end
      end
      @donors_by_date.push([donation_quantity, total_quantity - donation_quantity])
    end   
   


    total_clicks = clicks(@menu.bitly_url)
    @total_clickers_data = [total_clicks, @totals['Total Audience']]
    @total_donors_data = [@totals['Donations'], @totals['Total Audience'] - @totals['Donations']]
  end

  def shorten(url)
    print "Shortening ", url
    Bitly.use_api_version_3
    b = Bitly.new(Qrcode::Application.config.bitly_username, Qrcode::Application.config.bitly_api_key)
    begin
      output = b.shorten(url)
      return output.short_url
    rescue => e
      puts e.message
      puts e.backtrace.inspect
      return url
    end
  end

  def clicks(url)

    Bitly.use_api_version_3
    b = Bitly.new(Qrcode::Application.config.bitly_username, Qrcode::Application.config.bitly_api_key)
    output = b.clicks(url)
    return output.user_clicks
  end
end

app/helpers/menus_helper.rb
module MenusHelper
  def remove_link_unless_new_record(fields)
    unless fields.object.new_record?
      out = ''
      out << fields.hidden_field(:_delete)
      out << link_to_function("remove", "$(this).up('.#{fields.object.class.name.underscore}').hide(); $(this).previous().value = '1'")
      out
    end
  end
  
  # These use the current date, but they could be lots easier.
  # Maybe just keep a global counter which starts at 10 or so.
  # That would be good enough if we only build 1 new record in the controller.
  #
  # And this of course is only needed because Ryan's example uses JS to add new
  # records. If you just build a new one in the controller this is all unnecessary.
 def add_menu_item_link(name, form)

#    link_to_function name do |page|
      menu_item = render(:partial => 'menu_item', :locals => { :f => form, :menu_item => MenuItem.new })
    link_to_function name, escape_javascript(menu_item)
#      page << %{
#        var new_menu_item_id = "new_" + new Date().getTime();
#        $('#menu_items').append("#{ escape_javascript menu_item }".replace(/new_\\d+/g, new_menu_item_id));
#      }
#    end
  end
end

app/views/menus/_form.html.erb
<%= form_for(@menu) do |f| %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
    <legend>Menu</legend>
    <%= f.hidden_field :user_id, :value => current_user().id %>
    <div class="clearfix">
      <%= f.label :label %>
      <div class="input">
        <%= f.text_field :label, :class => "span3" %>
      </div>
    </div>
    <div class="clearfix">
      <%= f.label :image %>
      <div class="input">
        <%= f.text_field :image, :class => "span3" %>
      </div>
    </div>
    <div id="menu_items">
      <fieldset>
      <legend>Menu Items</legend>
      <div class="container">
      <%= f.nested_fields_for :menu_items do |mi_form| %>
        <div class="item">
        <div class="clearfix">
          <%= mi_form.label :label %>
          <div class="input">
            <%= mi_form.text_field :label, :class => "span3"%>
          </div>
        </div>
        <div class="clearfix">
          <%= mi_form.label :url %>
          <div class="input">
            <%= mi_form.text_field :url, :class => "span3"%>
          </div>
        </div>
        <div class="clearfix">
          <%= mi_form.label :image %>
          <div class="input">
            <%= mi_form.text_field :image, :class => "span3"%>
          </div>
        </div>
        <a href="#" class="remove btn small danger">remove</a>

        <%= mi_form.hidden_field :id %>
        <%= mi_form.hidden_field :_destroy %>
        </div>
      <% end %>
      </div>
      </fieldset>
      <a href="#" class="add btn small success">add menu item</a>
    </div>
    <div class="actions">
      <%= f.submit :class => "btn primary" %>
    </div>
  </fieldset>
<% end %>
<script type="text/javascript">
$(document).ready(function(e) {
  $('FORM').nestedFields();
});
</script>

app/views/menus/_metric_form.html.haml
= form_for @menu do |f| 
  - if @menu.errors.any?
    #error_explanation
      %h2 
        = pluralize(@menu.errors.count, "error")
        prohibited this menu from being saved:
      %ul
        - @menu.errors.full_messages.each do |msg|
          %li
            = msg
  %fieldset
    %legend
      = @menu.label
    #metrics
      %fieldset
        %legend Metrics
        .container
          = f.nested_fields_for :metric_dates, :render_template => false do |m_form|
            .item
              .clearfix
                = m_form.label :showdate
                .input
                  = m_form.text_field :showdate, :class => "span3"
              = m_form.nested_fields_for :metrics, :render_template => false do |m|
                .clearfix
                  = m.label :metric, "Quantity"
                  .input
                    %span{:class=>'uneditable-input span3'}
                      = m.object.metric
                    = m.hidden_field :metric, :class => 'metric-hidden'
                    = m.text_field :quantity, :class => "span2 inline", :type => "number"
              %a{:href=>"#",:class=>"remove btn danger small"} remove
              = m_form.hidden_field :id
              = m_form.hidden_field :_destroy
        = nested_fields_templates
      %a{:href=>"#", :class=>"add btn success small"}add show date
    .actions
      = f.submit :class => "btn primary"
    %script
      =raw @metric_types 
:javascript
  $(document).ready(function(e) {
    $('FORM').nestedFields({
      itemTemplateSelector: '.item.template.metric_date',
      beforeInsert: function(item) {
        var id = item.attr('data-record-id');

        var div = item.find('div.clearfix');

       for(i = 0; i < metric_types.length; i++) {
          var e = document.createElement('div');
          e.innerHTML = $('.item.metric.template').html().replace(/metric_dates_attributes_new_nested_item/g, 'metric_dates_attributes_' + id).replace(/menu\[metric_dates_attributes\]\[new_nested_item\]/g, 'menu[metric_dates_attributes][' + id + ']').replace(/metrics_attributes_new_nested_item/g, 'metrics_attributes_' + i).replace(/\[metrics_attributes\]\[new_nested_item\]/g, '[metrics_attributes][' + i + ']');
          var mt = $(e.childNodes.length === 0 ? "" : e.childNodes[0].nodeValue);
          mt.find('.uneditable-input').html(metric_types[i]);
          mt.find('.metric-hidden').val(metric_types[i]);

          mt.appendTo(div);
        }
        window.console.log(item);

      },
    });
  });

app/views/menus/edit.html.haml
%section{:id => "edit-menus"}
  %div{:class => "page-header"}
    %h1 Editing Menu
  %div{:class => "row"}
    %div{:class => "span4"}
      %p Give your menu a label. A good idea is the name of the show. Like 'Flippant Fuzz'. 
      %p The image link is for your company logo. Or the show logo. Something to put at the top of the menu to identify the menu to your audience.
      =link_to('Back', menus_path)
    %div{:class => "span12"}
      =render('form')

app/views/menus/edit_metric.html.haml
%section{:id => "edit-menus"}
  %div{:class => "page-header"}
    %h1 Edit Menu Metrics
  %div{:class => "row"}
    %div{:class => "span4"}
      %p Metrics allow us to capture the performance of your menu.
      %p For each show date enter values for each metric.
      =link_to('Back', menus_path)
    %div{:class => "span12"}
      =render('metric_form')

app/views/menus/index.html.haml
%section{:id => "forgot-password"}
  %div{:class => "page-header"}
    %h1 Menus
  %div{:class => "row"}
    %div{:class => "span4"}
      %p Here you can edit or view any existing menu.
      %p To create a new menu click the 'New Menu' link below.
      = link_to 'New Menu', new_menu_path
    %div{:class => "span12"}
      %table{:class => "table-striped"}
        %tr
          %th Label
          %th Image
          %th Actions
        - @menus.each do |menu|
          %tr
            %td 
              = link_to menu.label, edit_menu_path(menu)
            %td 
              %img{:src => menu.image}
            %td 
              = link_to 'View', view_menu_path(menu), :target => '_new'
              |
              = link_to 'Edit', edit_menu_path(menu)
              |
              = link_to 'Delete', menu, confirm: 'Are you sure?', method: :delete
              %br
              = link_to 'Metrics', :controller => 'menus', :action => 'edit_metric', :id => menu.id
              |
              = link_to 'Report', :controller => 'menus', :action => 'report', :id => menu.id
              %br
              = link_to 'Download QR Code', menu.bitly_url + '.qrcode', :target => '_new'
              %br
              = link_to 'Print instructions', help_menu_path(menu) + '.svg', :target => '_new'

        - if @menus.length == 0
          %tr
            %th{:colspan => 3} No menus found.

app/views/menus/new.html.haml
%section{:id => "forgot-password"}
  %div{:class => "page-header"}
    %h1 Create New Menu
  %div{:class => "row"}
    %div{:class => "span4"}
      %p Give your menu a label. A good idea is the name of the show. Like 'Flippant Fuzz'. 
      %p The image link is for your company logo. Or the show logo. Something to put at the top of the menu to identify the menu to your audience.
      =link_to('Back', menus_path)
    %div{:class => "span12"}
      =render('form')

app/views/menus/report.html.haml
%section{:id => "metrics"}
  %div{:class => "page-header"}
    %h1 Reports
  %div{:class => "row"}
    %div{:class => "span4"}
      %p Reports take data from link clicks and metrics and combines them to provide a comprehensive view of the success of your Mobile Menu.
      %p You can view more detailed reports from bit.ly by clicking on the stats links in the bottom left.
      =link_to('Back', menus_path)
    .span12 
      .row
        .span6
          %fieldset
            %legend Total Clickers
            %img{:src => Gchart.pie(:data => @total_clickers_data, :legend => ['Clickers', 'Non-Clickers'])}
        .span6
          %fieldset
            %legend Total Donors
            %img{:src => Gchart.pie(:data => @total_donors_data, :legend => ['Donors', 'Non-Donors'])}
      .row
        .span6
          %fieldset
            %legend Donors by Date
            %img{:src => Gchart.bar(:data => @donors_by_date, :axis_with_labels => 'x', :axis_labels => @donors_by_date_dates, :stacked => false, :legend => ['Donors', 'Non-Donors'],:bar_colors => 'FF0000,00FF00', :custom => 'xAxis.showTextEvery=2')}
        .span6
          %fieldset
            %legend Bitly Stats
            %ul
              %li
                %a{:target=>'_new', :href=>@menu.bitly_url + '+'} 
                  = @menu.label
                %ul
                  - @menu.menu_items.each do |menu_item|
                    %li
                      %a{:target=>'_new', :href=>menu_item.bitly_url + '+'}
                        = menu_item.label